/*
 * network.h
 *
 *  Created on: Oct 11, 2013
 *      Author: cs1120255
 */

#ifndef NETWORK_H_
#define NETWORK_H_

#include <iostream>
#include <cstring>
#include <string>
#include <vector>
#include"setEnvironment.h"
#include "globals.h"



using namespace std;
/* * Format for entry_code:: <year>|<university name><Department><increasing entry number>*/

/*!
*  \brief This is the main data structure of the graph generated by the generator threads. It contains all the information such as name, department, * courses, interests, etc.
*/
typedef struct GraphNode{

	bool isStudentNode;
	vector<Interest*> interest_array;
	Department* department;
	string name,entry_code;
	/*!
	* List of friends (this list contains only the pointers to the GraphNode which is a friend)
	*/
	vector<GraphNode*> friend_list; 
	vector<Course*> registered_courses;
	string hostel_name;
	int room_number;
	int floor;
	string house_name;
	int house_number;
	int year;
	int number;
public:
	~GraphNode()
	{}

}GraphNode;

/*!
* \brief Exposes various functions to the other modules.
*/
class Network{	
	public:
	/*!
	* List of the students and faculty nodes generated by the threads
	*/
	vector<GraphNode*> student_list,faculty_list;


	void addNode(GraphNode*);
	void makeFriends(GraphNode*, GraphNode*);
	void generateGraph(vector<GraphNode*>,vector<GraphNode*>);

	bool isStudent(GraphNode);
	bool isFaculty(GraphNode);
	vector<Interest*> giveInterests(GraphNode);
	Department* giveDepartment(GraphNode);
	string giveName(GraphNode);
	string entryNumber(GraphNode);
	string employeeCode(GraphNode);
	string giveHostelName(GraphNode);
	string giveHouseName(GraphNode);
	int giveHouseNumber(GraphNode);

};

#endif /* NETWORK_H_ */
